name: ramen_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.6+7

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  change_app_package_name: ^1.5.0
  geolocator: ^13.0.4
  google_place: ^0.4.7
  url_launcher: ^6.3.1
  flutter_spinkit: ^5.2.1
  flutter_launcher_icons: ^0.14.3
  go_router: ^15.0.0
  package_info_plus: ^8.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/sample.png
    - assets/images/human.png
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
